#pragma once

#include <string>
#include <vector>

typedef enum
{
	A3_FILE_NAME_UNKNOWN = 0,
	A3_FILE_NAME_LAENDER,
	A3_FILE_NAME_AVEREINE,
	A3_FILE_NAME_BONUS1,
	A3_FILE_NAME_FANGESA,
	A3_FILE_NAME_FANWAVES,
	A3_FILE_NAME_INTERNAT,
	A3_FILE_NAME_ISCHIRIS,
	A3_FILE_NAME_JUGEND1,
	A3_FILE_NAME_JUGEND10,
	A3_FILE_NAME_JUGEND11,
	A3_FILE_NAME_JUGEND12,
	A3_FILE_NAME_JUGEND13,
	A3_FILE_NAME_JUGEND14,
	A3_FILE_NAME_JUGEND15,
	A3_FILE_NAME_JUGEND16,
	A3_FILE_NAME_JUGEND17,
	A3_FILE_NAME_JUGEND18,
	A3_FILE_NAME_JUGEND2,
	A3_FILE_NAME_JUGEND3,
	A3_FILE_NAME_JUGEND4,
	A3_FILE_NAME_JUGEND5,
	A3_FILE_NAME_JUGEND6,
	A3_FILE_NAME_JUGEND7,
	A3_FILE_NAME_JUGEND8,
	A3_FILE_NAME_JUGEND9,
	A3_FILE_NAME_KLEINIG,
	A3_FILE_NAME_LANDSCHO,
	A3_FILE_NAME_LANDDEUT,
	A3_FILE_NAME_LANDENGL,
	A3_FILE_NAME_LANDFRAN,
	A3_FILE_NAME_LANDHOLL,
	A3_FILE_NAME_LANDITAL,
	A3_FILE_NAME_LANDOEST,
	A3_FILE_NAME_LANDPORT,
	A3_FILE_NAME_LANDSCHW,
	A3_FILE_NAME_LANDSPAN,
	A3_FILE_NAME_LANDTUER,
	A3_FILE_NAME_LIGA1BON,
	A3_FILE_NAME_LIGA1DEU,
	A3_FILE_NAME_LIGA1ENG,
	A3_FILE_NAME_LIGA1FRA,
	A3_FILE_NAME_LIGA1HOL,
	A3_FILE_NAME_LIGA1ITA,
	A3_FILE_NAME_LIGA1OES,
	A3_FILE_NAME_LIGA1POR,
	A3_FILE_NAME_LIGA1SCH,
	A3_FILE_NAME_LIGA1SPA,
	A3_FILE_NAME_LIGA1SWZ,
	A3_FILE_NAME_LIGA1TUE,
	A3_FILE_NAME_LIGA2DEU,
	A3_FILE_NAME_LIGA2ENG,
	A3_FILE_NAME_LIGA2FRA,
	A3_FILE_NAME_LIGA2ITA,
	A3_FILE_NAME_LIGA2SPA,
	A3_FILE_NAME_LIGA3ENG,
	A3_FILE_NAME_LIGA3ITA,
	A3_FILE_NAME_LIGA4ENG,
	A3_FILE_NAME_LIGARLNO,
	A3_FILE_NAME_LIGARLOS,
	A3_FILE_NAME_LIGARLSU,
	A3_FILE_NAME_LIGARLSW,
	A3_FILE_NAME_SONSPIEL,
	A3_FILE_NAME_EXSPIEL,
	A3_FILE_NAME_CLEAGUE,
	A3_FILE_NAME_EMWM,

	NO_OF_A3_FILE_NAME_TYPES
} A3_FILE_NAME_TYPE;

typedef enum
{
	A3_FILE_GROUP_UNKNOWN,
	A3_FILE_GROUP_LANDXXX,
	A3_FILE_GROUP_JUGENDXXX,
	A3_FILE_GROUP_INTERNAT,
	A3_FILE_GROUP_SONSPIELER,
	A3_FILE_GROUP_ISCHIRI,
	A3_FILE_GROUP_EXSPIEL,
	A3_FILE_GROUP_LAENDER,
	A3_FILE_GROUP_IVEREINE,
	A3_FILE_GROUP_CLEAGUE,
	A3_FILE_GROUP_EMWM,
	A3_FILE_GROUP_LIGAYXXX,
	
	NO_OF_A3_FILE_GROUP_TYPES
} A3_FILE_GROUP_TYPE;

std::string GetNameFromA3FileNameType (A3_FILE_NAME_TYPE);
A3_FILE_NAME_TYPE GetA3FileNameTypeFromFileName (std::string);
static A3_FILE_GROUP_TYPE GetA3FileGroupFromA3FileNameType (A3_FILE_NAME_TYPE);
void GetListOfA3DbFiles (std::vector<std::string>&);
A3_FILE_GROUP_TYPE GetA3FileGroupFromFileName (std::string);
std::string GetNameFromA3FileGroupType (A3_FILE_GROUP_TYPE);
A3_FILE_NAME_TYPE GetLandDefiningFileNameType (A3_FILE_NAME_TYPE);
