#pragma once

#include <string>
#include "misc_lib.h"

//////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////// ENUMS ///////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////

typedef enum
{
	STADION_ENUM_UNKNOWN,
	STADION_ENUM_ANZEIGETAFEL,
	STADION_ENUM_TRIBUENE,
	STADION_ENUM_ZUSTAND,
	STADION_ENUM_DACH_WAERMESTRAHLER,
	NO_OF_STADION_ENUM_TYPES
} STADION_ENUM_TYPE;

typedef enum
{
	STADION_BOOLEAN_UNKNOWN,
	STADION_BOOLEAN_AUSFAHRBARESSPIELFELD,
	STADION_BOOLEAN_AUTOBAHNANBINDUNG,
	STADION_BOOLEAN_BEHEIZBARESITZE,
	STADION_BOOLEAN_BERGE,
	STADION_BOOLEAN_BURG,
	STADION_BOOLEAN_CITYLAGE,
	STADION_BOOLEAN_FERNSEHTURM,
	STADION_BOOLEAN_FLUTLICHT,
	STADION_BOOLEAN_IMBESITZDESVEREINS,
	STADION_BOOLEAN_LAUFBAHN,
	STADION_BOOLEAN_LUXUSKABINEN,
	STADION_BOOLEAN_RASENHEIZUNG,
	STADION_BOOLEAN_SCHLOSS,
	STADION_BOOLEAN_SITZKISSEN,
	STADION_BOOLEAN_DACH_HAUPT,
	STADION_BOOLEAN_DACH_GEGEN,
	STADION_BOOLEAN_DACH_LINKS,
	STADION_BOOLEAN_DACH_RECHTS,
	STADION_BOOLEAN_WAERMESTRAHLER_HAUPT,
	STADION_BOOLEAN_WAERMESTRAHLER_GEGEN,
	STADION_BOOLEAN_WAERMESTRAHLER_LINKS,
	STADION_BOOLEAN_WAERMESTRAHLER_RECHTS,
	NO_OF_STADION_BOOLEAN_TYPES
} STADION_BOOLEAN_TYPE;

typedef enum
{
	STADION_ANZEIGETAFEL_UNKNOWN,
	STADION_ANZEIGETAFEL_KEINE_TAFEL,
	STADION_ANZEIGETAFEL_TORSCHILDER,
	STADION_ANZEIGETAFEL_KLEINE_LED_TAFEL,
	STADION_ANZEIGETAFEL_GROSSE_LED_TAFEL,
	STADION_ANZEIGETAFEL_VIDEOWAND,
	NO_OF_STADION_ANZEIGETAFEL_TYPES
} STADION_ANZEIGETAFEL_TYPE;

typedef enum
{
	STADION_TRIBUENE_UNKNOWN,
	STADION_TRIBUENE_HAUPT,
	STADION_TRIBUENE_GEGEN,
	STADION_TRIBUENE_LINKS,
	STADION_TRIBUENE_RECHTS,
	NO_OF_STADION_TRIBUENE_TYPES
} STADION_TRIBUENE_TYPE;

typedef enum
{
	STADION_ZUSTAND_UNKNOWN,
	STADION_ZUSTAND_NEU,
	STADION_ZUSTAND_FAST_NEU,
	STADION_ZUSTAND_UNMODERN,
	STADION_ZUSTAND_ANGESTAUBT,
	STADION_ZUSTAND_BAUFAELLIG,
	STADION_ZUSTAND_VERMODERT,
	STADION_ZUSTAND_VERFALLEN,
	NO_OF_STADION_ZUSTAND_TYPES
} STADION_ZUSTAND_TYPE;

typedef enum
{
	STADION_DACH_WAERMESTRAHLER_UNKNOWN,
	STADION_DACH_WAERMESTRAHLER_KEIN,
	STADION_DACH_WAERMESTRAHLER_HAUPT,
	STADION_DACH_WAERMESTRAHLER_GEGEN,
	STADION_DACH_WAERMESTRAHLER_LINKS,
	STADION_DACH_WAERMESTRAHLER_RECHTS,
	NO_OF_STADION_DACH_WAERMESTRAHLER_TYPES
} STADION_DACH_WAERMESTRAHLER_TYPE;

//////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////// FUNCTION FORWARD DECLARATIONS ///////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////

ENUM_VALUE_LIST& GetStadionEnumValueList (STADION_ENUM_TYPE, ENUM_VALUE_LIST&);
int GetStadionEnumValue (int, ENUM_VALUE_SIDE_TYPE, int);
std::string GetNameFromStadionEnumType (int);
std::string GetNameFromStadionAnzeigetafelType (int);
std::string GetNameFromStadionTribueneType (int);
std::string GetNameFromStadionZustandType (int);
std::string GetNameFromStadionDachWaermestrahlerType (int);

int GetValueFromStadionBooleanType (STADION_BOOLEAN_TYPE);
std::string GetNameFromStadionBooleanType (STADION_BOOLEAN_TYPE);
